In [48]:
from mxnet import nd

In [53]:
X = nd.arange(12)
X


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [54]:
X.shape


(12,)

In [55]:
X.size

12

In [56]:
X = X.reshape((3,4))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [57]:
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [58]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [59]:
Y = nd.array([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
Y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [61]:
nd.random.normal(0,1,shape=(3,4))


[[-0.68106437 -0.1353156   0.37723133  0.41016456]
 [ 0.5712682  -2.7579627   1.07628    -0.6141325 ]
 [ 1.8307649  -1.1468065   0.05383794 -2.5074806 ]]
<NDArray 3x4 @cpu(0)>

In [62]:
X + Y # 元素加法


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [63]:
X * Y # 元素乘法


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [64]:
X / Y # 元素除法


[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>

In [65]:
Y.exp() # 按元素做指数运算


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

In [66]:
nd.dot(X,Y.T) # 点乘


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [67]:
nd.concat(X,Y,dim=0), nd.concat(X,Y,dim=1)# 按维度连接

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [ 2.  1.  4.  3.]
  [ 1.  2.  3.  4.]
  [ 4.  3.  2.  1.]]
 <NDArray 6x4 @cpu(0)>,
 
 [[ 0.  1.  2.  3.  2.  1.  4.  3.]
  [ 4.  5.  6.  7.  1.  2.  3.  4.]
  [ 8.  9. 10. 11.  4.  3.  2.  1.]]
 <NDArray 3x8 @cpu(0)>)

In [68]:
X==Y # 判断每个位置是否相等，相等留下True


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [69]:
X.sum() # 求和


[66.]
<NDArray 1 @cpu(0)>

In [70]:
x.norm().asscalar()

30.91925

In [71]:
A = nd.arange(3).reshape((3,1))
B = nd.arange(2).reshape((1,2))
A,B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>,
 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [72]:
A + B # 广播机制


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [73]:
X[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [74]:
X[1,2] = 9

In [75]:
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [76]:
X[1:2,:]


[[4. 5. 9. 7.]]
<NDArray 1x4 @cpu(0)>

In [77]:
X[1:2, :] = 12
X


[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [78]:
before = id(Y)
Y = X + Y
id(Y) == before # 说明重新开辟内存了

False

In [80]:
# 指定到特定内存
Z = Y.zeros_like()
before = id(Z)
Z[:] = X + Y
id(Z) == before
#实际上这个还是开辟了新的内存然后复制进去的

True

In [81]:
# 利用运算符全称函数out参数进行指定存储空间，这样无需拷贝
nd.elemwise_add(X,Y,out=Z)
id(Z) == before

True

In [83]:
# 如果某值在后面的运算不会复用 用 X[:] = X+Y 或者X+=Y减少运算开支
before = id(X)
X += Y
id(X) == before

True

In [85]:
# NDarray 和 Numpy 互换
# Numpy 转 NDarray
import numpy as np
P = np.ones((2,3))
D = nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [87]:
# NDarray转Numpy
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [88]:
from mxnet import autograd, nd

In [90]:
x = nd.arange(4).reshape((4,1))

In [91]:
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>